# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-14 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
