# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-15 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0002_auto_20160514_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_tagger.ImageData')),
            ],
        ),
    ]
