# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0003_imagedatatag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='imagedatatag',
            name='image_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='image_tagger.ImageData'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='image_tagger.Objeto'),
        ),
    ]
