# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 02:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0004_auto_20160516_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedatatag',
            name='object',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='image_tagger.Objeto'),
            preserve_default=False,
        ),
    ]
