# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-16 02:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0005_imagedatatag_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageDataTag',
            new_name='Tag',
        ),
    ]
