# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0006_auto_20160516_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('originTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedToRelations', to='image_tagger.Tag')),
                ('targetTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedFromRelations', to='image_tagger.Tag')),
            ],
        ),
    ]
