# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0008_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(default='wonder', upload_to='wonder'),
            preserve_default=False,
        ),
    ]
