# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0011_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
