# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-14 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_tagger', '0012_auto_20161014_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_tagger.Dataset')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='users',
            field=models.ManyToManyField(related_name='datasets', through='image_tagger.DatasetMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
