# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-15 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0014_imagedata_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='dataset',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='image_tagger.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objeto',
            name='dataset',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='image_tagger.Dataset'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='dataset',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='image_tagger.Dataset'),
            preserve_default=False,
        ),
    ]
