# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-17 18:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_tagger', '0016_auto_20161017_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contribution',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contribution',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='contribution',
        ),
        migrations.AddField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 17, 18, 20, 13, 599824, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='image_tagger.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
