# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0018_auto_20161017_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_date', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2000)),
                ('file', models.FileField(upload_to=b'')),
            ],
        ),
    ]
