# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-14 21:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0019_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='file',
        ),
    ]
