# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0022_publication_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_types', to='image_tagger.Dataset'),
        ),
        migrations.AlterField(
            model_name='objecttype',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_types', to='image_tagger.Dataset'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_types', to='image_tagger.Dataset'),
        ),
    ]
