# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_tagger', '0023_auto_20170208_1306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('value', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together=set([('name', 'dataset')]),
        ),
        migrations.AlterUniqueTogether(
            name='attributetypevalue',
            unique_together=set([('name', 'attribute_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='datasetmembership',
            unique_together=set([('user', 'dataset')]),
        ),
        migrations.AlterUniqueTogether(
            name='objecttype',
            unique_together=set([('name', 'dataset')]),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set([('relation_type', 'originTag', 'targetTag')]),
        ),
        migrations.AlterUniqueTogether(
            name='relationtype',
            unique_together=set([('name', 'dataset')]),
        ),
    ]
