# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-08 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import image_tagger.models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0025_dataset_fixed_onthology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to=image_tagger.models.generate_unique_hard_to_guess_name),
        ),
    ]
