# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0029_auto_20170930_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='fixed_onthology',
            new_name='fixed_types',
        ),
    ]
