# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 23:46
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_tagger', '0030_auto_20170930_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='desired_number_of_contributions',
            field=models.IntegerField(default=3, help_text="Determines the number of users who should contribute an image before the system stops showing it with priority. Please note that this value should not be greater than the number of contributors in this dataset. If you don't know what this value means, better to leave it at the default value of 3.", validators=[django.core.validators.MinValueValidator(2)]),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='fixed_types',
            field=models.BooleanField(default=False, help_text='Determines whether contributors can create new types (object, relationships, etc.) or not. If set to true, only object types, attribute types, attribute value types, and relationship types defined in the system can be used.'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='public',
            field=models.BooleanField(default=False, help_text='Determines whether the publications of this dataset will be available to non logged users or not. If set to true, anyone will be able to download publications of this dataset from the public datasets area.'),
        ),
    ]
